/** Generated from CE Globals.c/GlobalsBase.c by scripts/x2m-colors.py. */
import { TerrainType } from '../Map/Grid';
export type TerrainColor = readonly [number, number, number, number, number, number, number, number];
export const CE_COLORS: Readonly<Record<string, TerrainColor>> = {
    descentBoltColor: [-40, -40, -40, 0, 0, 80, 80, 1],
    discordColor: [25, 0, 25, 66, 0, 0, 0, 1],
    poisonColor: [0, 0, 0, 10, 50, 10, 0, 1],
    beckonColor: [10, 10, 10, 5, 5, 5, 50, 1],
    invulnerabilityColor: [25, 0, 25, 0, 0, 66, 0, 1],
    fireBoltColor: [500, 150, 0, 45, 30, 0, 0, 1],
    yendorLightColor: [50, -100, 30, 0, 0, 0, 0, 1],
    flamedancerCoronaColor: [500, 150, 100, 45, 30, 0, 0, 1],
    undiscoveredColor: [0, 0, 0, 0, 0, 0, 0, 0],
    wallForeColor: [7, 7, 7, 3, 3, 3, 0, 0],
    wallBackColorStart: [45, 40, 40, 15, 0, 5, 20, 0],
    wallBackColorEnd: [40, 30, 35, 0, 20, 30, 20, 0],
    mudWallForeColor: [55, 45, 0, 5, 5, 5, 1, 0],
    mudWallBackColor: [20, 12, 3, 8, 4, 3, 0, 0],
    graniteBackColor: [10, 10, 10, 0, 0, 0, 0, 0],
    floorForeColor: [30, 30, 30, 0, 0, 0, 35, 0],
    floorBackColorStart: [2, 2, 10, 2, 2, 0, 0, 0],
    floorBackColorEnd: [5, 5, 5, 2, 2, 0, 0, 0],
    stairsBackColor: [15, 15, 5, 0, 0, 0, 0, 0],
    firstStairsBackColor: [10, 10, 25, 0, 0, 0, 0, 0],
    refuseBackColor: [6, 5, 3, 2, 2, 0, 0, 0],
    rubbleBackColor: [7, 7, 8, 2, 2, 1, 0, 0],
    bloodflowerForeColor: [30, 5, 40, 5, 1, 3, 0, 0],
    bloodflowerPodForeColor: [50, 5, 25, 5, 1, 3, 0, 0],
    bloodflowerBackColor: [15, 3, 10, 3, 1, 3, 0, 0],
    bedrollBackColor: [10, 8, 5, 1, 1, 0, 0, 0],
    obsidianBackColor: [6, 0, 8, 2, 0, 3, 0, 0],
    carpetForeColor: [23, 30, 38, 0, 0, 0, 0, 0],
    carpetBackColor: [15, 8, 5, 0, 0, 0, 0, 0],
    marbleForeColor: [30, 23, 38, 0, 0, 0, 0, 0],
    marbleBackColor: [6, 5, 13, 1, 0, 1, 0, 0],
    doorForeColor: [70, 35, 15, 0, 0, 0, 0, 0],
    doorBackColor: [30, 10, 5, 0, 0, 0, 0, 0],
    ironDoorForeColor: [500, 500, 500, 0, 0, 0, 0, 0],
    ironDoorBackColor: [15, 15, 30, 0, 0, 0, 0, 0],
    bridgeFrontColor: [33, 12, 12, 12, 7, 2, 0, 0],
    bridgeBackColor: [12, 3, 2, 3, 2, 1, 0, 0],
    statueBackColor: [20, 20, 20, 0, 0, 0, 0, 0],
    glyphColor: [20, 5, 5, 50, 0, 0, 0, 1],
    glyphLightColor: [150, 0, 0, 150, 0, 0, 0, 1],
    sacredGlyphColor: [5, 20, 5, 0, 50, 0, 0, 1],
    sacredGlyphLightColor: [45, 150, 60, 25, 80, 25, 0, 1],
    minersLightStartColor: [180, 180, 180, 0, 0, 0, 0, 0],
    minersLightEndColor: [90, 90, 120, 0, 0, 0, 0, 0],
    torchColor: [150, 75, 30, 0, 30, 20, 0, 1],
    deepWaterForeColor: [5, 8, 20, 0, 4, 15, 10, 1],
    deepWaterBackColorStart: [5, 10, 31, 5, 5, 5, 6, 1],
    deepWaterBackColorEnd: [5, 8, 20, 2, 3, 5, 5, 1],
    shallowWaterForeColor: [28, 28, 60, 0, 0, 10, 10, 1],
    shallowWaterBackColorStart: [20, 20, 60, 0, 0, 10, 10, 1],
    shallowWaterBackColorEnd: [12, 15, 40, 0, 0, 5, 5, 1],
    mudForeColor: [18, 14, 5, 5, 5, 0, 0, 0],
    mudBackColor: [23, 17, 7, 5, 5, 0, 0, 0],
    chasmForeColor: [7, 7, 15, 4, 4, 8, 0, 0],
    chasmEdgeBackColorStart: [5, 5, 25, 2, 2, 2, 0, 0],
    chasmEdgeBackColorEnd: [8, 8, 20, 2, 2, 2, 0, 0],
    fireForeColor: [70, 20, 0, 15, 10, 0, 0, 1],
    lavaForeColor: [20, 20, 20, 100, 10, 0, 0, 1],
    brimstoneForeColor: [100, 50, 10, 0, 50, 40, 0, 1],
    brimstoneBackColor: [18, 12, 9, 0, 0, 5, 0, 0],
    lavaBackColor: [70, 20, 0, 15, 10, 0, 0, 1],
    acidBackColor: [15, 80, 25, 5, 15, 10, 0, 1],
    lightningColor: [100, 150, 500, 50, 50, 0, 50, 1],
    fungusLightColor: [2, 11, 11, 4, 3, 3, 0, 1],
    lavaLightColor: [47, 13, 0, 10, 7, 0, 0, 1],
    deepWaterLightColor: [10, 30, 100, 0, 30, 100, 0, 1],
    grassColor: [15, 40, 15, 15, 50, 15, 10, 0],
    deadGrassColor: [20, 13, 0, 20, 10, 5, 10, 0],
    fungusColor: [15, 50, 50, 0, 25, 0, 30, 1],
    grayFungusColor: [30, 30, 30, 5, 5, 5, 10, 0],
    foliageColor: [25, 100, 25, 15, 0, 15, 0, 0],
    deadFoliageColor: [20, 13, 0, 30, 15, 0, 20, 0],
    lichenColor: [50, 5, 25, 10, 0, 5, 0, 1],
    hayColor: [70, 55, 5, 0, 20, 20, 0, 0],
    ashForeColor: [20, 20, 20, 0, 0, 0, 20, 0],
    bonesForeColor: [80, 80, 30, 5, 5, 35, 5, 0],
    ectoplasmColor: [45, 20, 55, 25, 0, 25, 5, 0],
    forceFieldColor: [0, 25, 25, 0, 25, 25, 0, 1],
    wallCrystalColor: [40, 40, 60, 20, 20, 40, 0, 1],
    altarForeColor: [5, 7, 9, 0, 0, 0, 0, 0],
    altarBackColor: [35, 18, 18, 0, 0, 0, 0, 0],
    greenAltarBackColor: [18, 25, 18, 0, 0, 0, 0, 0],
    goldAltarBackColor: [25, 24, 12, 0, 0, 0, 0, 0],
    pedestalBackColor: [10, 5, 20, 0, 0, 0, 0, 0],
    goblinColor: [44, 33, 22, 0, 0, 0, 0, 0],
    jackalColor: [60, 42, 27, 0, 0, 0, 0, 0],
    ogreColor: [60, 25, 25, 0, 0, 0, 0, 0],
    eelColor: [30, 12, 12, 0, 0, 0, 0, 0],
    goblinConjurerColor: [67, 10, 100, 0, 0, 0, 0, 0],
    spectralBladeColor: [15, 15, 60, 0, 0, 70, 50, 1],
    spectralImageColor: [13, 0, 0, 25, 0, 0, 0, 1],
    toadColor: [40, 65, 30, 0, 0, 0, 0, 0],
    trollColor: [40, 60, 15, 0, 0, 0, 0, 0],
    centipedeColor: [75, 25, 85, 0, 0, 0, 0, 0],
    dragonColor: [20, 80, 15, 0, 0, 0, 0, 0],
    krakenColor: [100, 55, 55, 0, 0, 0, 0, 0],
    salamanderColor: [40, 10, 0, 8, 5, 0, 0, 1],
    pixieColor: [60, 60, 60, 40, 40, 40, 0, 1],
    darPriestessColor: [0, 50, 50, 0, 0, 0, 0, 0],
    darMageColor: [50, 50, 0, 0, 0, 0, 0, 0],
    wraithColor: [66, 66, 25, 0, 0, 0, 0, 0],
    pinkJellyColor: [100, 40, 40, 5, 5, 5, 20, 1],
    wormColor: [80, 60, 40, 0, 0, 0, 0, 0],
    sentinelColor: [3, 3, 30, 0, 0, 10, 0, 1],
    goblinMysticColor: [10, 67, 100, 0, 0, 0, 0, 0],
    ifritColor: [50, 10, 100, 75, 0, 20, 0, 1],
    phoenixColor: [100, 0, 0, 0, 100, 0, 0, 1],
    torchLightColor: [75, 38, 15, 0, 15, 7, 0, 1],
    hauntedTorchColor: [75, 20, 40, 30, 10, 0, 0, 1],
    hauntedTorchLightColor: [67, 10, 10, 20, 4, 0, 0, 1],
    ifritLightColor: [0, 10, 150, 100, 0, 100, 0, 1],
    unicornLightColor: [-50, -50, -50, 250, 250, 250, 0, 1],
    wispLightColor: [75, 100, 250, 33, 10, 0, 0, 1],
    summonedImageLightColor: [200, 0, 75, 0, 0, 0, 0, 1],
    spectralBladeLightColor: [40, 0, 230, 0, 0, 0, 0, 1],
    ectoplasmLightColor: [23, 10, 28, 13, 0, 13, 3, 0],
    explosionColor: [10, 8, 2, 0, 2, 2, 0, 1],
    explosiveAuraColor: [2000, 0, -1000, 200, 200, 0, 0, 1],
    sacrificeTargetColor: [100, -100, -300, 0, 100, 100, 0, 1],
    dartFlashColor: [500, 500, 500, 0, 2, 2, 0, 1],
    lichLightColor: [-50, 80, 30, 0, 0, 20, 0, 1],
    forceFieldLightColor: [10, 10, 10, 0, 50, 50, 0, 1],
    crystalWallLightColor: [10, 10, 10, 0, 0, 50, 0, 1],
    sunLightColor: [100, 100, 75, 0, 0, 0, 0, 0],
    fungusForestLightColor: [30, 40, 60, 0, 0, 0, 40, 1],
    fungusTrampledLightColor: [10, 10, 10, 0, 50, 50, 0, 1],
    redFlashColor: [100, 10, 10, 0, 0, 0, 0, 0],
    darknessPatchColor: [-10, -10, -10, 0, 0, 0, 0, 0],
    darknessCloudColor: [-20, -20, -20, 0, 0, 0, 0, 0],
    magicMapFlashColor: [60, 20, 60, 0, 0, 0, 0, 0],
    sentinelLightColor: [20, 20, 120, 10, 10, 60, 0, 1],
    telepathyColor: [30, 30, 130, 0, 0, 0, 0, 0],
    confusionLightColor: [10, 10, 10, 10, 10, 10, 0, 1],
    portalActivateLightColor: [300, 400, 500, 0, 0, 0, 0, 1],
    descentLightColor: [20, 20, 70, 0, 0, 0, 0, 0],
    algaeBlueLightColor: [20, 15, 50, 0, 0, 0, 0, 0],
    algaeGreenLightColor: [15, 50, 20, 0, 0, 0, 0, 0],
    scrollProtectionColor: [375, 750, 0, 0, 0, 0, 0, 1],
    scrollEnchantmentColor: [250, 225, 300, 0, 0, 450, 0, 1],
    potionStrengthColor: [1000, 0, 400, 600, 0, 0, 0, 1],
    empowermentFlashColor: [500, 1000, 600, 0, 500, 0, 0, 1],
    genericFlashColor: [800, 800, 800, 0, 0, 0, 0, 0],
    summoningFlashColor: [0, 0, 0, 600, 0, 1200, 0, 1],
    fireFlashColor: [750, 225, 0, 100, 50, 0, 0, 1],
    explosionFlareColor: [10000, 6000, 1000, 0, 0, 0, 0, 0],
    quietusFlashColor: [0, -1000, -200, 0, 0, 0, 0, 1],
    slayingFlashColor: [-1000, -200, 0, 0, 0, 0, 0, 1],
    colorDim25: [25, 25, 25, 25, 25, 25, 25, 0],
    colorMultiplier100: [100, 100, 100, 100, 100, 100, 100, 0],
    memoryColor: [25, 25, 50, 20, 20, 20, 0, 0],
    memoryOverlay: [25, 25, 50, 0, 0, 0, 0, 0],
    magicMapColor: [60, 20, 60, 60, 20, 60, 0, 0],
    clairvoyanceColor: [50, 90, 50, 50, 90, 50, 66, 0],
    telepathyMultiplier: [30, 30, 130, 30, 30, 130, 66, 0],
    omniscienceColor: [140, 100, 60, 140, 100, 60, 90, 0],
    basicLightColor: [180, 180, 180, 180, 180, 180, 180, 0],
    humanBloodColor: [60, 20, 10, 15, 0, 0, 15, 0],
    insectBloodColor: [10, 60, 20, 0, 15, 0, 15, 0],
    vomitColor: [60, 50, 5, 0, 15, 15, 0, 0],
    urineColor: [70, 70, 40, 0, 0, 0, 10, 0],
    methaneColor: [45, 60, 15, 0, 0, 0, 0, 0],
    poisonGasColor: [75, 25, 85, 0, 0, 0, 0, 0],
    confusionGasColor: [60, 60, 60, 40, 40, 40, 0, 1],
    itemColor: [100, 95, -30, 0, 0, 0, 0, 0],
    blueBar: [15, 10, 50, 0, 0, 0, 0, 0],
    redBar: [45, 10, 15, 0, 0, 0, 0, 0],
    hiliteColor: [100, 100, 0, 0, 0, 0, 0, 0],
    interfaceBoxColor: [7, 6, 15, 0, 0, 0, 0, 0],
    interfaceButtonColor: [18, 15, 38, 0, 0, 0, 0, 0],
    buttonHoverColor: [100, 70, 40, 0, 0, 0, 0, 0],
    titleButtonColor: [23, 15, 30, 0, 0, 0, 0, 0],
    playerInvisibleColor: [30, 30, 40, 0, 0, 80, 0, 1],
    playerInLightColor: [100, 90, 30, 0, 0, 0, 0, 0],
    playerInShadowColor: [60, 60, 100, 0, 0, 0, 0, 0],
    playerInDarknessColor: [40, 40, 65, 0, 0, 0, 0, 0],
    inLightMultiplierColor: [150, 150, 75, 150, 150, 75, 100, 1],
    inDarknessMultiplierColor: [66, 66, 120, 66, 66, 120, 66, 1],
    goodMessageColor: [60, 50, 100, 0, 0, 0, 0, 0],
    badMessageColor: [100, 50, 60, 0, 0, 0, 0, 0],
    advancementMessageColor: [50, 100, 60, 0, 0, 0, 0, 0],
    itemMessageColor: [100, 100, 50, 0, 0, 0, 0, 0],
    flavorTextColor: [50, 40, 90, 0, 0, 0, 0, 0],
    backgroundMessageColor: [60, 20, 70, 0, 0, 0, 0, 0],
    superVictoryColor: [150, 100, 300, 0, 0, 0, 0, 0],
    flameSourceColor: [20, 7, 7, 60, 40, 40, 0, 1],
    flameSourceColorSecondary: [7, 2, 0, 10, 0, 0, 0, 1],
    flameTitleColor: [0, 0, 0, 9, 9, 15, 0, 1],
    white: [100, 100, 100, 0, 0, 0, 0, 0],
    gray: [50, 50, 50, 0, 0, 0, 0, 0],
    darkGray: [30, 30, 30, 0, 0, 0, 0, 0],
    veryDarkGray: [15, 15, 15, 0, 0, 0, 0, 0],
    black: [0, 0, 0, 0, 0, 0, 0, 0],
    yellow: [100, 100, 0, 0, 0, 0, 0, 0],
    darkYellow: [50, 50, 0, 0, 0, 0, 0, 0],
    teal: [30, 100, 100, 0, 0, 0, 0, 0],
    purple: [100, 0, 100, 0, 0, 0, 0, 0],
    darkPurple: [50, 0, 50, 0, 0, 0, 0, 0],
    brown: [60, 40, 0, 0, 0, 0, 0, 0],
    green: [0, 100, 0, 0, 0, 0, 0, 0],
    darkGreen: [0, 50, 0, 0, 0, 0, 0, 0],
    orange: [100, 50, 0, 0, 0, 0, 0, 0],
    darkOrange: [50, 25, 0, 0, 0, 0, 0, 0],
    blue: [0, 0, 100, 0, 0, 0, 0, 0],
    darkBlue: [0, 0, 50, 0, 0, 0, 0, 0],
    darkTurquoise: [0, 40, 65, 0, 0, 0, 0, 0],
    lightBlue: [40, 40, 100, 0, 0, 0, 0, 0],
    pink: [100, 60, 66, 0, 0, 0, 0, 0],
    darkPink: [50, 30, 33, 0, 0, 0, 0, 0],
    red: [100, 0, 0, 0, 0, 0, 0, 0],
    darkRed: [50, 0, 0, 0, 0, 0, 0, 0],
    tanColor: [80, 67, 15, 0, 0, 0, 0, 0],
    rainbow: [-70, -70, -70, 170, 170, 170, 0, 1],
};
export const CE_DEPTH_COLORS: Readonly<Record<string, readonly [string, string]>> = {
  "minersLight": [
    "minersLightStartColor",
    "minersLightEndColor"
  ],
  "wallBackColor": [
    "wallBackColorStart",
    "wallBackColorEnd"
  ],
  "deepWaterBackColor": [
    "deepWaterBackColorStart",
    "deepWaterBackColorEnd"
  ],
  "shallowWaterBackColor": [
    "shallowWaterBackColorStart",
    "shallowWaterBackColorEnd"
  ],
  "floorBackColor": [
    "floorBackColorStart",
    "floorBackColorEnd"
  ],
  "chasmEdgeBackColor": [
    "chasmEdgeBackColorStart",
    "chasmEdgeBackColorEnd"
  ]
};
export const TERRAIN_COLOR_NAMES: Record<TerrainType, readonly [string | null, string | null]> = {
    // X4-R1: CE world catalog additions.
    [TerrainType.BLOODFLOWER_POD]: ["bloodflowerPodForeColor", null],
    [TerrainType.HEALING_CLOUD]: [null, "darkRed"],
    [TerrainType.HAY]: ["hayColor", "refuseBackColor"],
    [TerrainType.URINE]: ["urineColor", null],
    [TerrainType.JUNK]: ["mudBackColor", "refuseBackColor"],
    [TerrainType.BURNED_CARPET]: ["ashForeColor", null],
    [TerrainType.GREEN_BLOOD]: ["insectBloodColor", null],
    [TerrainType.PURPLE_BLOOD]: ["poisonGasColor", null],
    [TerrainType.ACID_SPLATTER]: ["acidBackColor", null],
    [TerrainType.WORM_BLOOD]: ["wormColor", null],
    [TerrainType.UNICORN_POOP]: ["white", null],
    [TerrainType.GUARDIAN_GLOW]: [null, null],
    [TerrainType.FLAMEDANCER_FIRE]: ["fireForeColor", null],
    [TerrainType.DART_EXPLOSION]: ["white", null],
    [TerrainType.CREATURE_FIRE]: ["white", null],

    [TerrainType.NOTHING]: ["black", "black"],
    [TerrainType.GRANITE]: ["wallBackColor", "graniteBackColor"],
    [TerrainType.FLOOR]: ["floorForeColor", "floorBackColor"],
    [TerrainType.WALL]: ["wallForeColor", "wallBackColor"],
    [TerrainType.DOOR]: ["doorForeColor", "doorBackColor"],
    [TerrainType.OPEN_DOOR]: ["doorForeColor", "doorBackColor"],
    [TerrainType.WATER_SHALLOW]: ["shallowWaterForeColor", "shallowWaterBackColor"],
    [TerrainType.WATER_DEEP]: ["deepWaterForeColor", "deepWaterBackColor"],
    [TerrainType.CHASM]: ["chasmForeColor", "black"],
    [TerrainType.LAVA]: ["fireForeColor", "lavaBackColor"],
    [TerrainType.GRASS]: ["grassColor", null],
    [TerrainType.FOLIAGE]: ["foliageColor", null],
    [TerrainType.BOG]: ["mudForeColor", "mudBackColor"],
    [TerrainType.STAIRS_UP]: ["itemColor", "stairsBackColor"],
    [TerrainType.STAIRS_DOWN]: ["itemColor", "stairsBackColor"],
    [TerrainType.CHARRED_FLOOR]: ["ashForeColor", null],
    [TerrainType.SIGN]: ["glyphColor", null],
    [TerrainType.RESET_PLATE]: ["darkGray", "chasmEdgeBackColor"],
    [TerrainType.TRAP]: ["poisonGasColor", null],
    [TerrainType.SECRET_DOOR]: ["wallForeColor", "wallBackColor"],
    [TerrainType.PRESSURE_PLATE]: ["white", "chasmEdgeBackColor"],
    [TerrainType.LOCKED_DOOR]: ["ironDoorForeColor", "ironDoorBackColor"],
    [TerrainType.ALTAR]: ["altarForeColor", "altarBackColor"],
    [TerrainType.WEB]: ["white", null],
    [TerrainType.BLOOD]: ["humanBloodColor", null],
    [TerrainType.MUD]: ["mudForeColor", "mudBackColor"],
    [TerrainType.CHASM_EDGE]: ["white", "chasmEdgeBackColor"],
    [TerrainType.OBSIDIAN]: ["darkGray", "obsidianBackColor"],
    [TerrainType.BRIDGE]: ["bridgeFrontColor", "bridgeBackColor"],
    [TerrainType.BRIDGE_EDGE]: ["bridgeFrontColor", "bridgeBackColor"],
    [TerrainType.INERT_BRIMSTONE]: ["brimstoneForeColor", "brimstoneBackColor"],
    [TerrainType.PLAIN_FIRE]: ["fireForeColor", null],
    [TerrainType.EMBERS]: ["fireForeColor", null],
    [TerrainType.ASH]: ["ashForeColor", null],
    [TerrainType.POISON_GAS]: [null, "poisonGasColor"],
    [TerrainType.CONFUSION_GAS]: [null, "confusionGasColor"],
    [TerrainType.STEAM]: [null, "white"],
    [TerrainType.GAS_FIRE]: ["fireForeColor", null],
    [TerrainType.METHANE_GAS]: [null, "methaneColor"],
    [TerrainType.PARALYSIS_GAS]: [null, "pink"],
    [TerrainType.GAS_EXPLOSION]: ["yellow", null],
    [TerrainType.HOLE]: ["chasmForeColor", "black"],
    [TerrainType.HOLE_EDGE]: ["white", "chasmEdgeBackColor"],
    [TerrainType.FORCEFIELD]: ["forceFieldColor", "forceFieldColor"],
    [TerrainType.FORCEFIELD_MELT]: ["black", "forceFieldColor"],
    [TerrainType.CRYSTAL_WALL]: ["wallCrystalColor", "wallCrystalColor"],
    [TerrainType.SACRED_GLYPH]: ["sacredGlyphColor", null],
    [TerrainType.CARPET]: ["carpetForeColor", "carpetBackColor"],
    [TerrainType.STATUE_INERT]: ["wallBackColor", "statueBackColor"],
    [TerrainType.PEDESTAL]: ["altarForeColor", "pedestalBackColor"],
    [TerrainType.STATUE_INERT_DOORWAY]: ["wallBackColor", "statueBackColor"],
    [TerrainType.WOODEN_BARRICADE]: ["doorForeColor", "floorBackColor"],
    [TerrainType.TRAP_DOOR_HIDDEN]: ["floorForeColor", "floorBackColor"],
    [TerrainType.MACHINE_GLYPH]: ["glyphColor", null],
    [TerrainType.PORTCULLIS_CLOSED]: ["gray", "floorBackColor"],
    [TerrainType.WORM_TUNNEL_OUTER_WALL]: ["wallForeColor", "wallBackColor"],
    [TerrainType.WALL_LEVER_HIDDEN]: ["wallForeColor", "wallBackColor"],
    [TerrainType.GAS_TRAP_PARALYSIS]: ["pink", null],
    [TerrainType.GAS_TRAP_PARALYSIS_HIDDEN]: ["floorForeColor", "floorBackColor"],
    [TerrainType.MACHINE_PARALYSIS_VENT_HIDDEN]: ["floorForeColor", "floorBackColor"],
    [TerrainType.MACHINE_METHANE_VENT_HIDDEN]: ["floorForeColor", "floorBackColor"],
    [TerrainType.PILOT_LIGHT_DORMANT]: ["torchLightColor", "wallBackColor"],
    [TerrainType.ALTAR_CAGE_OPEN]: ["altarForeColor", "altarBackColor"],
    [TerrainType.ALTAR_CAGE_RETRACTABLE]: ["altarBackColor", "veryDarkGray"],
    [TerrainType.COMMUTATION_ALTAR]: ["altarForeColor", "greenAltarBackColor"],
    [TerrainType.RESURRECTION_ALTAR]: ["altarForeColor", "goldAltarBackColor"],
    [TerrainType.AMULET_SWITCH]: ["floorForeColor", "floorBackColor"],
    [TerrainType.STATUE_INSTACRACK]: ["wallBackColor", "statueBackColor"],
    [TerrainType.TORCH_WALL]: ["torchColor", "wallBackColor"],
    [TerrainType.ALTAR_SWITCH]: ["altarForeColor", "altarBackColor"],
    [TerrainType.MACHINE_TRIGGER_FLOOR]: ["floorForeColor", "floorBackColor"],
    [TerrainType.STATUE_DORMANT]: ["wallBackColor", "statueBackColor"],
    [TerrainType.WALL_MONSTER_DORMANT]: ["wallForeColor", "wallBackColor"],
    [TerrainType.RAT_TRAP_WALL_DORMANT]: ["wallForeColor", "wallBackColor"],
    [TerrainType.STATUE_DORMANT_DOORWAY]: ["wallBackColor", "statueBackColor"],
    [TerrainType.TURRET_DORMANT]: ["wallForeColor", "wallBackColor"],
    [TerrainType.MONSTER_CAGE_OPEN]: ["floorBackColor", "veryDarkGray"],
    [TerrainType.MONSTER_CAGE_CLOSED]: ["gray", "darkGray"],
    [TerrainType.MACHINE_POISON_GAS_VENT_HIDDEN]: ["floorForeColor", "floorBackColor"],
    [TerrainType.PORTCULLIS_DORMANT]: ["floorForeColor", "floorBackColor"],
    [TerrainType.WALL_LEVER_HIDDEN_DORMANT]: ["wallForeColor", "wallBackColor"],
    [TerrainType.BONES]: ["bonesForeColor", null],
    [TerrainType.COFFIN_CLOSED]: ["bridgeFrontColor", "bridgeBackColor"],
    [TerrainType.ALTAR_KEYHOLE]: ["altarForeColor", "altarBackColor"],
    [TerrainType.ALTAR_SWITCH_RETRACTING]: ["altarForeColor", "altarBackColor"],
    [TerrainType.BRAZIER]: ["fireForeColor", "statueBackColor"],
    [TerrainType.DEMONIC_STATUE]: ["wallBackColor", "statueBackColor"],
    [TerrainType.FLAMETHROWER_HIDDEN]: ["floorForeColor", "floorBackColor"],
    [TerrainType.GAS_TRAP_POISON_HIDDEN]: ["floorForeColor", "floorBackColor"],
    [TerrainType.MANACLE_L]: ["gray", null],
    [TerrainType.MANACLE_T]: ["gray", null],
    [TerrainType.PORTAL]: ["wallBackColor", "floorBackColor"],
    [TerrainType.SACRIFICE_ALTAR_DORMANT]: ["altarForeColor", "altarBackColor"],
    [TerrainType.SACRIFICE_CAGE_DORMANT]: ["altarBackColor", "veryDarkGray"],
    [TerrainType.DEAD_GRASS]: ["deadGrassColor", null],
    [TerrainType.VOMIT]: ["vomitColor", null],
    [TerrainType.LUMINESCENT_FUNGUS]: ["fungusColor", null],
    [TerrainType.DEAD_FOLIAGE]: ["deadFoliageColor", null],
    [TerrainType.RUBBLE]: ["gray", null],
    [TerrainType.GRAY_FUNGUS]: ["grayFungusColor", null],
    [TerrainType.WORM_TUNNEL_MARKER_DORMANT]: [null, null],
    [TerrainType.BLOODFLOWER_STALK]: ["bloodflowerForeColor", "bloodflowerBackColor"],
    [TerrainType.HAVEN_BEDROLL]: ["black", "bedrollBackColor"],
    [TerrainType.FLOOR_FLOODABLE]: ["floorForeColor", "floorBackColor"],
    [TerrainType.CHASM_WITH_HIDDEN_BRIDGE]: ["chasmForeColor", "black"],
    [TerrainType.LAVA_RETRACTABLE]: ["fireForeColor", "lavaBackColor"],
    [TerrainType.MUD_FLOOR]: ["mudBackColor", "refuseBackColor"],
    [TerrainType.MUD_WALL]: ["mudWallForeColor", "mudWallBackColor"],
    [TerrainType.MUD_DOORWAY]: ["mudWallForeColor", "refuseBackColor"],
    [TerrainType.MARBLE_FLOOR]: ["marbleForeColor", "marbleBackColor"],
    [TerrainType.FLOOD_TRAP]: ["blue", null],
    [TerrainType.ELECTRIC_CRYSTAL_OFF]: ["wallCrystalColor", "graniteBackColor"],
    [TerrainType.TURRET_LEVER]: ["wallForeColor", "wallBackColor"],
    [TerrainType.HAUNTED_TORCH_DORMANT]: ["torchColor", "wallBackColor"],
    [TerrainType.DARK_FLOOR_DORMANT]: ["floorForeColor", "floorBackColor"],
    [TerrainType.MACHINE_FLOOD_WATER_DORMANT]: ["shallowWaterForeColor", "shallowWaterBackColor"],
    [TerrainType.MACHINE_FLOOD_WATER_SPREADING]: ["shallowWaterForeColor", "shallowWaterBackColor"],
    [TerrainType.MACHINE_COLLAPSE_EDGE_DORMANT]: ["floorForeColor", "floorBackColor"],
    [TerrainType.MACHINE_COLLAPSE_EDGE_SPREADING]: ["white", "chasmEdgeBackColor"],
    [TerrainType.CHASM_WITH_HIDDEN_BRIDGE_ACTIVE]: ["white", "chasmEdgeBackColor"],
    [TerrainType.STONE_BRIDGE]: ["white", "chasmEdgeBackColor"],
    [TerrainType.LAVA_RETRACTING]: ["fireForeColor", "lavaBackColor"],
    [TerrainType.FLOOD_WATER_SHALLOW]: ["shallowWaterForeColor", "shallowWaterBackColor"],
    [TerrainType.FLOOD_WATER_DEEP]: ["deepWaterForeColor", "deepWaterBackColor"],
    [TerrainType.MACHINE_CHASM_EDGE]: ["white", "chasmEdgeBackColor"],
    [TerrainType.PUDDLE]: ["shallowWaterBackColor", null],
    [TerrainType.MACHINE_MUD_DORMANT]: ["mudForeColor", "mudBackColor"],
    [TerrainType.DARK_FLOOR_DARKENING]: ["floorForeColor", "floorBackColor"],
    [TerrainType.DARK_FLOOR]: ["floorForeColor", "floorBackColor"],
    [TerrainType.ECTOPLASM]: ["ectoplasmColor", null],
    [TerrainType.HAUNTED_TORCH_TRANSITIONING]: ["torchColor", "wallBackColor"],
    [TerrainType.HAUNTED_TORCH]: ["hauntedTorchColor", "wallBackColor"],
    [TerrainType.ELECTRIC_CRYSTAL_ON]: ["white", "wallCrystalColor"],
    [TerrainType.MACHINE_GLYPH_INACTIVE]: ["glyphColor", null],
    [TerrainType.STENCH_SMOKE_GAS]: [null, "vomitColor"],
    [TerrainType.ANCIENT_SPIRIT_VINES]: ["lichenColor", null],
    [TerrainType.ANCIENT_SPIRIT_GRASS]: ["grassColor", null],
    [TerrainType.DUNGEON_PORTAL]: ["wallCrystalColor", "firstStairsBackColor"],
    [TerrainType.ITEM_FIRE]: ["white", null],
    [TerrainType.TRAMPLED_FOLIAGE]: ["foliageColor", null],
    [TerrainType.ACTIVE_BRIMSTONE]: ["brimstoneForeColor", "brimstoneBackColor"],
    [TerrainType.BRIMSTONE_FIRE]: ["fireForeColor", null],
    [TerrainType.OPEN_IRON_DOOR_INERT]: ["white", "ironDoorBackColor"],
    [TerrainType.BRIDGE_FALLING]: ["bridgeFrontColor", "bridgeBackColor"],
    [TerrainType.MACHINE_PRESSURE_PLATE_USED]: ["darkGray", "chasmEdgeBackColor"],
    [TerrainType.TRAP_DOOR]: ["chasmForeColor", "black"],
    [TerrainType.WALL_LEVER]: ["wallForeColor", "wallBackColor"],
    [TerrainType.WALL_LEVER_PULLED]: ["wallForeColor", "wallBackColor"],
    [TerrainType.MACHINE_TRIGGER_FLOOR_REPEATING]: [null, null],
    [TerrainType.MACHINE_METHANE_VENT_DORMANT]: ["floorForeColor", null],
    [TerrainType.MACHINE_METHANE_VENT]: ["floorForeColor", null],
    [TerrainType.PILOT_LIGHT]: ["fireForeColor", "wallBackColor"],
    [TerrainType.MACHINE_PARALYSIS_VENT]: ["pink", null],
    [TerrainType.MACHINE_POISON_GAS_VENT_DORMANT]: ["floorForeColor", null],
    [TerrainType.MACHINE_POISON_GAS_VENT]: ["floorForeColor", null],
    [TerrainType.GAS_TRAP_POISON]: ["poisonGasColor", null],
    [TerrainType.FLAMETHROWER]: ["red", null],
    [TerrainType.ALTAR_CAGE_CLOSED]: ["altarBackColor", "veryDarkGray"],
    [TerrainType.COMMUTATION_ALTAR_INERT]: ["black", "greenAltarBackColor"],
    [TerrainType.PIPE_GLOWING]: ["veryDarkGray", null],
    [TerrainType.RESURRECTION_ALTAR_INERT]: ["black", "goldAltarBackColor"],
    [TerrainType.SACRIFICE_ALTAR]: ["altarForeColor", "altarBackColor"],
    [TerrainType.PIPE_INERT]: ["black", null],
    [TerrainType.SACRIFICE_LAVA]: ["fireForeColor", "lavaBackColor"],
    [TerrainType.RAT_TRAP_WALL_CRACKING]: ["wallForeColor", "wallBackColor"],
    [TerrainType.STATUE_CRACKING]: ["wallBackColor", "statueBackColor"],
    [TerrainType.COFFIN_OPEN]: ["black", "bridgeBackColor"],
    [TerrainType.WORM_TUNNEL_MARKER_ACTIVE]: [null, null],
    [TerrainType.PORTAL_LIGHT]: [null, null],
    [TerrainType.FUNGUS_FOREST]: ["fungusForestLightColor", null],
    [TerrainType.TRAMPLED_FUNGUS_FOREST]: ["fungusForestLightColor", null],
    [TerrainType.SUNLIGHT_POOL]: ["floorForeColor", "floorBackColor"],
    [TerrainType.DARKNESS_PATCH]: ["floorForeColor", "floorBackColor"],
    [TerrainType.DEEP_WATER_ALGAE_WELL]: ["floorForeColor", "floorBackColor"],
    [TerrainType.DEEP_WATER_ALGAE_1]: ["deepWaterForeColor", "deepWaterBackColor"],
    [TerrainType.DEEP_WATER_ALGAE_2]: ["deepWaterForeColor", "deepWaterBackColor"],
    [TerrainType.NET_TRAP]: ["tanColor", null],
    [TerrainType.NET_TRAP_HIDDEN]: ["floorForeColor", "floorBackColor"],
    [TerrainType.NETTING]: ["brown", null],
    [TerrainType.ALARM_TRAP]: ["gray", null],
    [TerrainType.ALARM_TRAP_HIDDEN]: ["floorForeColor", "floorBackColor"],
    [TerrainType.GAS_TRAP_CONFUSION]: ["confusionGasColor", null],
    [TerrainType.GAS_TRAP_CONFUSION_HIDDEN]: ["floorForeColor", "floorBackColor"],
    [TerrainType.FLOOD_TRAP_HIDDEN]: ["floorForeColor", "floorBackColor"],
    [TerrainType.STEAM_VENT]: ["gray", null],
    [TerrainType.DEWAR_CAUSTIC_GAS]: ["poisonGasColor", "darkGray"],
    [TerrainType.DEWAR_CONFUSION_GAS]: ["confusionGasColor", "darkGray"],
    [TerrainType.DEWAR_PARALYSIS_GAS]: ["pink", "darkGray"],
    [TerrainType.DEWAR_METHANE_GAS]: ["methaneColor", "darkGray"],
    [TerrainType.BROKEN_GLASS]: ["white", null],
    [TerrainType.LICHEN]: ["lichenColor", null],
    [TerrainType.DARKNESS_CLOUD]: [null, null],
    [TerrainType.ROT_GAS]: [null, "vomitColor"],
};
