/**
 * R-1（渲染纯重构轮）特征化测试 + 结构守卫。
 *
 * 本轮是"结构先行、行为逐位不变"的重构：把 GameCanvas.vue 内联的
 * 「格子/实体 → 外观」决策抽成 src/engine/UI/Appearance.ts 纯函数。
 * 本文件做两件事：
 *
 *  1. terrainAppearance 的逐枚举期望由 CE tileCatalog、颜色与字形源生成；
 *     cellAppearance / entityAppearance 对三态（可见/记忆/未探索）与
 *     三类实体逐一钉死，包括幻觉掷骰的调用次数与顺序这类"怪癖"。
 *  2. 结构守卫：钉死 GameCanvas.vue 里**不得再出现外观决策**
 *     （颜色/字形字面量、决策 switch、决策 API 引用、直接幻觉掷骰），
 *     防止决策在未来的 UI 轮里又漏回 SFC。
 *
 * 新地形须在 CE 别名映射与生成黄金表中登记。
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { TerrainType, Cell } from '../engine/Map/Grid';
import { GasType, type GasCell } from '../engine/Environment/Gas';
import type { LightChannels } from '../engine/Lighting/LightMap';
import {
    terrainAppearance,
    cellAppearance,
    itemAppearance,
    monsterAppearance,
    playerAppearance,
    entityAppearance,
    HALLUCINATION_COLORS,
    HALLUCINATION_CHARS,
    G_FIRE_CHAR,
    FIRE_FORE_COLOR,
    PARALYSIS_GAS_BG,
    METHANE_GAS_BG,
    PARALYSIS_GAS_FG,
    METHANE_GAS_FG,
    GAS_OVERLAY_CHAR,
    type CosmeticRng,
    type CellAppearanceContext,
    type EntityAppearanceContext,
} from '../engine/UI/Appearance';
import { Item, ItemCategory } from '../engine/Items/Item';
import { MonsterState, type Monster } from '../entities/Monster';
import { Player } from '../entities/Player';
import priorTerrainGoldens from './fixtures/u21c-ce-terrain.json';
import x2gTerrainGoldens from './fixtures/x2g-ce-terrain.json';
import x4r1TerrainGoldens from './fixtures/x4-r1-ce-terrain.json';
// CE-source additions; retain the historical 190-row fixture byte-for-byte.
const ceTerrainGoldens = { ...priorTerrainGoldens, ...x2gTerrainGoldens, ...x4r1TerrainGoldens };

// ════════════════════════ 工具 ════════════════════════

/** 从枚举取全部成员值（TS 数字枚举的 Object.values 含反向键名，滤掉字符串）。 */
const ALL_TERRAINS: TerrainType[] = Object.values(TerrainType).filter(
    (v): v is TerrainType => typeof v === 'number',
);

/** CE source parsed goldens; generated by scripts/u21c-ce-appearance.mjs. */
const EXPECTED_VISIBLE: Record<TerrainType, { char: string; color: string; bgColor: number | null }> = Object.fromEntries(
    Object.entries(ceTerrainGoldens).map(([name, { char, color, bgColor }]) => [TerrainType[name as keyof typeof TerrainType], { char, color, bgColor }]),
) as Record<TerrainType, { char: string; color: string; bgColor: number | null }>;
const floor = ceTerrainGoldens.FLOOR;
const lightColor = (hex: string, channels: readonly number[]) => '#' + [0, 1, 2].map((i) => {
    const base = parseInt(hex.slice(1 + i * 2, 3 + i * 2), 16);
    const level = Math.max(0, channels[i]!);
    const adjusted = level > 150 ? Math.trunc(Math.sqrt(level / 150) * 150) : level;
    return Math.min(255, Math.trunc(base * adjusted / 100)).toString(16).padStart(2, '0');
}).join('');
const lightBg = (value: number, channels: readonly number[]) => parseInt(lightColor('#' + value.toString(16).padStart(6, '0'), channels).slice(1), 16);

/** 造 Cell（terrain 走 setter 写回归属层）。只用于 DUNGEON/SURFACE 层地形。 */
function makeCell(
    terrain: TerrainType,
    opts: { visible?: boolean; explored?: boolean; memory?: boolean } = {},
): Cell {
    const c = new Cell(3, 4);
    c.terrain = terrain;
    c.isVisible = opts.visible ?? false;
    c.isExplored = opts.explored ?? (opts.visible ?? false);
    c.hasMemory = opts.memory ?? false;
    return c;
}

/** 记录型假幻觉随机：percent 依序弹 percents（弹尽返回 false），pick 恒取首项并记录来源序列。 */
interface ScriptedCosmetic extends CosmeticRng {
    percentCalls: number[];
    pickSources: string[];
}
function scriptedCosmetic(percents: boolean[]): ScriptedCosmetic {
    let i = 0;
    return {
        percentCalls: [],
        pickSources: [],
        percent(p: number) {
            this.percentCalls.push(p);
            return percents[i++] ?? false;
        },
        pick<T>(list: readonly T[]): T {
            this.pickSources.push(list === HALLUCINATION_COLORS ? 'colors' : list === HALLUCINATION_CHARS ? 'chars' : 'other');
            return list[0]!;
        },
    };
}

/** CE 量级的满强白光三通道（矿灯色 {180,180,180} 一类；乘数 1.0 的Identity 光）。 */
const IDENTITY_LIGHT: LightChannels = { r: 100, g: 100, b: 100 };

function cellCtx(overrides: Partial<CellAppearanceContext> = {}): CellAppearanceContext {
    return {
        gas: undefined,
        lightChannels: null,
        groundItem: null,
        carriedItem: null,
        hallucinating: false,
        cosmetic: scriptedCosmetic([]),
        ...overrides,
    };
}

function entityCtx(overrides: Partial<EntityAppearanceContext> = {}): EntityAppearanceContext {
    return {
        cellVisible: true,
        cellHasMemory: false,
        telepathy: false,
        hallucinating: false,
        cosmetic: scriptedCosmetic([]),
        ...overrides,
    };
}

function gas(type: GasType, density = 100): GasCell {
    return { type, density };
}

/** 轻量 Monster 替身：monsterAppearance 只读 hp/isAlly/state/char/color 五个字段。 */
function makeMonster(overrides: Partial<Pick<Monster, 'hp' | 'isAlly' | 'state' | 'char' | 'color'>> = {}): Monster {
    const base = {
        loc: { x: 1, y: 2 },
        hp: 10,
        isAlly: false,
        state: MonsterState.HUNTING,
        char: 'r',
        color: 0xaa0044,
    };
    return { ...base, ...overrides } as unknown as Monster;
}

// ════════════════════════ terrainAppearance 特征化 ════════════════════════

describe('R-1 terrainAppearance 特征化（穷举钉死）', () => {
    it('穷举表覆盖 TerrainType 全部成员（当前 208 个）、成员值无重复', () => {
        // 成员数变化（新增地形）时此断言翻红——按文件头说明更新期望表。
        // V-2b-2b：+6（CARPET/STATUE_INERT/PEDESTAL/STATUE_INERT_DOORWAY/
        // WOODEN_BARRICADE/TRAP_DOOR_HIDDEN），47 → 53。
        // V-2b-3：+9（MACHINE_GLYPH/PORTCULLIS_CLOSED/WORM_TUNNEL_OUTER_WALL/
        // WALL_LEVER_HIDDEN/GAS_TRAP_PARALYSIS/_HIDDEN/MACHINE_PARALYSIS_VENT_
        // HIDDEN/MACHINE_METHANE_VENT_HIDDEN/PILOT_LIGHT_DORMANT），53 → 62。
        // V-2b-4：+7（ALTAR_CAGE_OPEN/ALTAR_CAGE_RETRACTABLE/COMMUTATION_ALTAR/
        // RESURRECTION_ALTAR/AMULET_SWITCH/STATUE_INSTACRACK/TORCH_WALL——
        // 祭坛族轮七条蓝图的地形载体），62 → 69。
        // V-2b-5：+7（ALTAR_SWITCH/MACHINE_TRIGGER_FLOOR/STATUE_DORMANT/
        // WALL_MONSTER_DORMANT/RAT_TRAP_WALL_DORMANT/STATUE_DORMANT_DOORWAY/
        // TURRET_DORMANT——休眠唤醒轮八条蓝图的地形载体），69 → 76。
        // V-2b-6：+6（MONSTER_CAGE_OPEN/MONSTER_CAGE_CLOSED/
        // MACHINE_POISON_GAS_VENT_HIDDEN/PORTCULLIS_DORMANT/
        // WALL_LEVER_HIDDEN_DORMANT/BONES——钥匙轮 10/35/40 号蓝图的载体），
        // 76 → 82。
        // V-2b-7：DF 特征系统轮 19 条入列（CE Globals.c:355/363/367/372/377/
        // 387/448/449/450/457/465/473/484/486/543/546/547/568/573），82 → 101。
        // V-2b-8：BLOODFLOWER_STALK / HAVEN_BEDROLL 两条新成员。
        // V-2b-9a：十二条新载体成员，103 → 115；RUBBLE 已存在。
        // V-2b-9b：九条活动态/效果落点，115 → 124；补完轮补齐
        // MACHINE_CHASM_EDGE / PUDDLE，124 → 126；9c 七条效果载体 126 → 133。
        // U08 adds two CE terrain carriers; preserve the old-universe count.
        expect(ALL_TERRAINS.filter(t => t !== TerrainType.ANCIENT_SPIRIT_VINES && t !== TerrainType.ANCIENT_SPIRIT_GRASS && t !== TerrainType.DUNGEON_PORTAL && t !== TerrainType.ITEM_FIRE && ![TerrainType.BLOODFLOWER_POD, TerrainType.HEALING_CLOUD, TerrainType.HAY, TerrainType.URINE, TerrainType.JUNK, TerrainType.BURNED_CARPET, TerrainType.GREEN_BLOOD, TerrainType.PURPLE_BLOOD, TerrainType.ACID_SPLATTER, TerrainType.WORM_BLOOD, TerrainType.UNICORN_POOP, TerrainType.GUARDIAN_GLOW, TerrainType.FLAMEDANCER_FIRE, TerrainType.DART_EXPLOSION, TerrainType.CREATURE_FIRE, TerrainType.LICHEN, TerrainType.DARKNESS_CLOUD, TerrainType.ROT_GAS, TerrainType.TRAMPLED_FOLIAGE, TerrainType.ACTIVE_BRIMSTONE, TerrainType.BRIMSTONE_FIRE, TerrainType.OPEN_IRON_DOOR_INERT, TerrainType.BRIDGE_FALLING, TerrainType.MACHINE_PRESSURE_PLATE_USED, TerrainType.TRAP_DOOR, TerrainType.WALL_LEVER, TerrainType.WALL_LEVER_PULLED, TerrainType.MACHINE_TRIGGER_FLOOR_REPEATING, TerrainType.MACHINE_METHANE_VENT_DORMANT, TerrainType.MACHINE_METHANE_VENT, TerrainType.PILOT_LIGHT, TerrainType.MACHINE_PARALYSIS_VENT, TerrainType.MACHINE_POISON_GAS_VENT_DORMANT, TerrainType.MACHINE_POISON_GAS_VENT, TerrainType.GAS_TRAP_POISON, TerrainType.FLAMETHROWER, TerrainType.ALTAR_CAGE_CLOSED, TerrainType.COMMUTATION_ALTAR_INERT, TerrainType.PIPE_GLOWING, TerrainType.RESURRECTION_ALTAR_INERT, TerrainType.SACRIFICE_ALTAR, TerrainType.PIPE_INERT, TerrainType.SACRIFICE_LAVA, TerrainType.RAT_TRAP_WALL_CRACKING, TerrainType.STATUE_CRACKING, TerrainType.COFFIN_OPEN, TerrainType.WORM_TUNNEL_MARKER_ACTIVE, TerrainType.PORTAL_LIGHT, TerrainType.FUNGUS_FOREST, TerrainType.TRAMPLED_FUNGUS_FOREST, TerrainType.SUNLIGHT_POOL, TerrainType.DARKNESS_PATCH, TerrainType.DEEP_WATER_ALGAE_WELL, TerrainType.DEEP_WATER_ALGAE_1, TerrainType.DEEP_WATER_ALGAE_2, TerrainType.NET_TRAP, TerrainType.NET_TRAP_HIDDEN, TerrainType.NETTING, TerrainType.ALARM_TRAP, TerrainType.ALARM_TRAP_HIDDEN, TerrainType.GAS_TRAP_CONFUSION, TerrainType.GAS_TRAP_CONFUSION_HIDDEN, TerrainType.FLOOD_TRAP_HIDDEN, TerrainType.STEAM_VENT, TerrainType.DEWAR_CAUSTIC_GAS, TerrainType.DEWAR_CONFUSION_GAS, TerrainType.DEWAR_PARALYSIS_GAS, TerrainType.DEWAR_METHANE_GAS, TerrainType.BROKEN_GLASS].includes(t)).length).toBe(135);
        expect(ALL_TERRAINS.length).toBe(208);
        expect(new Set(ALL_TERRAINS).size).toBe(ALL_TERRAINS.length);
    });

    it('可见态：每个成员的 {char, color, bgColor} 全等钉死', () => {
        expect(Object.keys(ceTerrainGoldens)).toHaveLength(ALL_TERRAINS.length);
        for (const t of ALL_TERRAINS) {
            expect(terrainAppearance(t, true), `TerrainType[${t}] 可见态`).toEqual(EXPECTED_VISIBLE[t]);
        }
    });

    it('不可见（记忆）态：统一变暗 #333333 / 0x111111，字形不变', () => {
        for (const t of ALL_TERRAINS) {
            const visible = EXPECTED_VISIBLE[t];
            expect(terrainAppearance(t, false), `TerrainType[${t}] 不可见态`).toEqual({
                char: visible.char,
                color: '#333333',
                bgColor: visible.bgColor === null ? null : 0x111111,
            });
        }
    });
});

// ════════════════════════ cellAppearance 三态 ════════════════════════

describe('R-1 cellAppearance：未探索 / 可见 / 记忆 三态', () => {
    it('未探索且不可见 → null（什么都不画）', () => {
        expect(cellAppearance(makeCell(TerrainType.FLOOR), cellCtx())).toBeNull();
        expect(cellAppearance(makeCell(TerrainType.STAIRS_DOWN), cellCtx())).toBeNull();
        expect(cellAppearance(makeCell(TerrainType.GRANITE), cellCtx({ hallucinating: true }))).toBeNull();
    });

    it('可见但无光 → 近黑（#222222 / 0x050505）——可见≠亮，这是原行为', () => {
        expect(cellAppearance(makeCell(TerrainType.FLOOR, { visible: true }), cellCtx())).toEqual({
            char: floor.char, color: '#222222', bgColor: 0x050505,
        });
        expect(cellAppearance(makeCell(TerrainType.DOOR, { visible: true }), cellCtx())).toEqual({
            char: '+', color: '#222222', bgColor: 0x050505,
        });
        // 全零通道同样走"无光"分支
        expect(
            cellAppearance(makeCell(TerrainType.DOOR, { visible: true }), cellCtx({ lightChannels: { r: 0, g: 0, b: 0 } })),
        ).toEqual({ char: '+', color: '#222222', bgColor: 0x050505 });
    });

    it('可见但有光 → CE 逐通道乘法：{100,100,100} 是恒等乘数，颜色原样', () => {
        // UI-1 第 7 条反转：旧实现是向光色按 intensity×0.8/0.5 混合；
        // 现在是 CE applyColorMultiplier（IO.c:1517-1530），乘数 =
        // adjustedLightValue(通道)/100——{100,100,100} 时乘数恰为 1。
        const visual = cellAppearance(
            makeCell(TerrainType.FLOOR, { visible: true }),
            cellCtx({ lightChannels: IDENTITY_LIGHT }),
        )!;
        expect(visual).toEqual({ char: floor.char, color: floor.color, bgColor: floor.bgColor });
    });

    it('可见但弱光 → 逐通道线性变暗（trunc(base*50/100)），不再被抬向光色', () => {
        const visual = cellAppearance(
            makeCell(TerrainType.FLOOR, { visible: true }),
            cellCtx({ lightChannels: { r: 50, g: 50, b: 50 } }),
        )!;
        expect(visual.color).toBe(lightColor(floor.color, [50, 50, 50]));
        expect(visual.bgColor).toBe(lightBg(floor.bgColor, [50, 50, 50]));
    });

    it('过亮光（>100）先平方根压回再乘，颜色向饱和抬升——旧混合公式给不出的效果', () => {
        // adjusted(180) = trunc(sqrt(180/150)*150) = 164（IO.c:1732-1737）
        const visual = cellAppearance(
            makeCell(TerrainType.FLOOR, { visible: true }),
            cellCtx({ lightChannels: { r: 180, g: 180, b: 180 } }),
        )!;
        expect(visual.color).toBe(lightColor(floor.color, [180, 180, 180]));
        expect(visual.bgColor).toBe(lightBg(floor.bgColor, [180, 180, 180]));
        expect(visual.color).not.toBe(lightColor(floor.color, [180, 180, 180].map(v => Math.trunc(v * 0.8))));
    });

    it('有色光是逐通道的：红通道亮、绿蓝通道灭 → 基色只剩红（混向单色的旧公式必红）', () => {
        const visual = cellAppearance(
            makeCell(TerrainType.FLOOR, { visible: true }),
            cellCtx({ lightChannels: { r: 100, g: 20, b: 0 } }),
        )!;
        expect(visual.color).toBe(lightColor(floor.color, [100, 20, 0]));
    });

    it('记忆态（已探索未可见）普通地形 → #333333 / 0x111111', () => {
        expect(cellAppearance(makeCell(TerrainType.FLOOR, { explored: true, memory: true }), cellCtx())).toEqual({
            char: floor.char, color: '#333333', bgColor: 0x111111,
        });
    });

    it('记忆态楼梯保持明亮（#ffffff / 0x222222）——原实现的楼梯特例', () => {
        expect(cellAppearance(makeCell(TerrainType.STAIRS_DOWN, { explored: true, memory: true }), cellCtx())).toEqual({
            char: '>', color: '#ffffff', bgColor: 0x222222,
        });
        expect(cellAppearance(makeCell(TerrainType.STAIRS_UP, { explored: true, memory: true }), cellCtx())).toEqual({
            char: '<', color: '#ffffff', bgColor: 0x222222,
        });
    });

    it('已探索但 hasMemory=false 且不可见 → 走 terrainAppearance 的变暗（同一视觉）', () => {
        // 钉死 else-if 结构：memory 分支不触发时仍有基础变暗
        expect(cellAppearance(makeCell(TerrainType.FLOOR, { explored: true, memory: false }), cellCtx())).toEqual({
            char: floor.char, color: '#333333', bgColor: 0x111111,
        });
    });
});

describe('R-1 cellAppearance：燃烧 / 气体 / 幻觉覆盖', () => {
    it('可见燃烧格（PLAIN_FIRE）无光 → CE 火字形压暗、无底色（UI-1 反转：不再有 "*" 覆盖层）', () => {
        const visual = cellAppearance(makeCell(TerrainType.PLAIN_FIRE, { visible: true }), cellCtx())!;
        expect(visual.char).toBe(G_FIRE_CHAR);
        expect(visual.color).toBe('#222222');
        expect(visual.bgColor).toBeNull(); // CE PLAIN_FIRE backColor = 0，无光分支不改 null
    });

    it('可见燃烧格 + 恒等光 → "*" 覆盖层已移除，CE 火外观原样可见（UI-1 反转）', () => {
        const visual = cellAppearance(
            makeCell(TerrainType.PLAIN_FIRE, { visible: true }),
            cellCtx({ lightChannels: IDENTITY_LIGHT }),
        )!;
        expect(visual.char).toBe(G_FIRE_CHAR);
        expect(visual.color).toBe(FIRE_FORE_COLOR);
        expect(visual.bgColor).toBeNull(); // CE PLAIN_FIRE backColor = 0
    });

    it('毒气覆盖可见格：bg 0x660066、"~"/#ff55ff（恒等光下原样）', () => {
        const visual = cellAppearance(
            makeCell(TerrainType.FLOOR, { visible: true }),
            cellCtx({ gas: gas(GasType.POISON), lightChannels: IDENTITY_LIGHT }),
        )!;
        expect(visual.char).toBe('~');
        expect(visual.color).toBe('#ff55ff');
        expect(visual.bgColor).toBe(0x660066);
    });

    it('燃烧格 + 毒气并存：bg 仍被毒气覆盖，但字形保住火字形（!isBurning 守卫；UI-1 后字形 = CE 火字形）', () => {
        const visual = cellAppearance(
            makeCell(TerrainType.PLAIN_FIRE, { visible: true }),
            cellCtx({ gas: gas(GasType.POISON), lightChannels: IDENTITY_LIGHT }),
        )!;
        expect(visual.char).toBe(G_FIRE_CHAR);
        expect(visual.color).toBe(FIRE_FORE_COLOR); // 火前景不被毒气字形覆盖
        expect(visual.bgColor).toBe(0x660066);      // 毒气 bg 后写生效
    });

    it('六种气体各就各位（bg 覆盖 + 字形/颜色；PARALYSIS/METHANE 为 UI-1 第 4 条反转）', () => {
        const combos: Array<[GasType, string, string, number]> = [
            [GasType.POISON, '~', '#ff55ff', 0x660066],
            [GasType.STEAM, '*', '#ffffff', 0xaaaaaa],
            [GasType.CONFUSION, '?', '#55ffff', 0x006666],
            [GasType.CREEPING_DEATH, '~', '#ff4444', 0x440000],
            [GasType.PARALYSIS, GAS_OVERLAY_CHAR, PARALYSIS_GAS_FG, PARALYSIS_GAS_BG],
            [GasType.METHANE, GAS_OVERLAY_CHAR, METHANE_GAS_FG, METHANE_GAS_BG],
        ];
        for (const [type, char, color, bg] of combos) {
            const visual = cellAppearance(
                makeCell(TerrainType.FLOOR, { visible: true }),
                cellCtx({ gas: gas(type), lightChannels: IDENTITY_LIGHT }),
            )!;
            expect(visual.char, `GasType[${type}] 字形`).toBe(char);
            expect(visual.color, `GasType[${type}] 颜色`).toBe(color);
            expect(visual.bgColor, `GasType[${type}] bg`).toBe(bg);
        }
    });

    it('气体 density=0 → 无覆盖（原 if (gas && gas.density > 0) 门）', () => {
        const visual = cellAppearance(
            makeCell(TerrainType.FLOOR, { visible: true }),
            cellCtx({ gas: gas(GasType.POISON, 0), lightChannels: IDENTITY_LIGHT }),
        )!;
        expect(visual.char).toBe(floor.char);
        expect(visual.color).toBe(floor.color); // 与"无气体+恒等光"完全一致
        expect(visual.bgColor).toBe(floor.bgColor);
    });

    it('PARALYSIS/METHANE 气体现在有渲染分支（UI-1 第 4 条反转旧留痕：此前钉死"无分支"）', () => {
        // 旧留痕断言（R-1 时）："PARALYSIS/METHANE 气体没有渲染分支（现状钉死——UI-1 欠账）"
        // UI-1 偿还该欠账，按「留痕反转」改为断言新事实。
        for (const type of [GasType.PARALYSIS, GasType.METHANE]) {
            const visual = cellAppearance(
                makeCell(TerrainType.FLOOR, { visible: true }),
                cellCtx({ gas: gas(type, 999), lightChannels: IDENTITY_LIGHT }),
            )!;
            expect(visual.char, `GasType[${type}]`).not.toBe(floor.char);
            expect(visual.bgColor, `GasType[${type}]`).not.toBe(floor.bgColor);
        }
        // 燃烧格上气体字形让位（!isBurning 守卫在两个新分支同样生效）
        const onFire = cellAppearance(
            makeCell(TerrainType.GAS_FIRE, { visible: true }),
            cellCtx({ gas: gas(GasType.METHANE, 999), lightChannels: IDENTITY_LIGHT }),
        )!;
        expect(onFire.char).toBe(G_FIRE_CHAR);
        expect(onFire.bgColor).toBe(METHANE_GAS_BG);
    });

    it('幻觉：percent(15) 中 → 取幻觉色/字形（发生在无光压暗之后）；不中 → 原样', () => {
        const hit = scriptedCosmetic([true]);
        const visual = cellAppearance(makeCell(TerrainType.FLOOR, { visible: true }), cellCtx({ hallucinating: true, cosmetic: hit }))!;
        expect(hit.percentCalls).toEqual([15]);
        expect(hit.pickSources).toEqual(['colors', 'chars']); // 先色后字
        expect(visual.char).toBe('*'); // HALLUCINATION_CHARS[0]
        expect(visual.color).toBe('#ff66ff'); // HALLUCINATION_COLORS[0]，盖过无光的 #222222

        const miss = scriptedCosmetic([false]);
        const plain = cellAppearance(makeCell(TerrainType.FLOOR, { visible: true }), cellCtx({ hallucinating: true, cosmetic: miss }))!;
        expect(miss.percentCalls).toEqual([15]);
        expect(miss.pickSources).toEqual([]);
        expect(plain).toEqual({ char: floor.char, color: '#222222', bgColor: 0x050505 });
    });

    it('不可见格不消耗幻觉掷骰（记忆分支零 cosmetic 调用）', () => {
        const cos = scriptedCosmetic([true, true, true]);
        cellAppearance(makeCell(TerrainType.FLOOR, { explored: true, memory: true }), cellCtx({ hallucinating: true, cosmetic: cos }));
        expect(cos.percentCalls).toEqual([]);
    });
});

// ════════════════════════ entityAppearance 三类实体 ════════════════════════

describe('R-1 entityAppearance：物品', () => {
    const item = new Item('测试物品', '!', 0xff00ff, ItemCategory.POTION);

    it('可见常态 → 原字形原色、interactive', () => {
        expect(itemAppearance(item, entityCtx())).toEqual({ char: '!', color: 0xff00ff, interactive: true });
    });

    it('幻觉双掷怪癖：两次独立 percent(30)——[中,不中] = "!" 配原色（逐位保留）', () => {
        const cos = scriptedCosmetic([true, false]);
        const visual = itemAppearance(item, entityCtx({ hallucinating: true, cosmetic: cos }))!;
        expect(cos.percentCalls).toEqual([30, 30]);
        expect(cos.pickSources).toEqual([]);
        expect(visual).toEqual({ char: '!', color: 0xff00ff, interactive: true });
    });

    it('幻觉双掷：[不中,中] = 原字形配幻觉色', () => {
        const cos = scriptedCosmetic([false, true]);
        const visual = itemAppearance(item, entityCtx({ hallucinating: true, cosmetic: cos }))!;
        expect(visual).toEqual({ char: '!', color: '#ff66ff', interactive: true });
        expect(cos.pickSources).toEqual(['colors']);
    });

    it('幻觉双掷：[中,中] = "!" 配幻觉色', () => {
        const cos = scriptedCosmetic([true, true]);
        expect(itemAppearance(item, entityCtx({ hallucinating: true, cosmetic: cos }))!).toEqual({
            char: '!', color: '#ff66ff', interactive: true,
        });
    });

    it('非幻觉不掷骰', () => {
        const cos = scriptedCosmetic([]);
        itemAppearance(item, entityCtx({ hallucinating: false, cosmetic: cos }));
        expect(cos.percentCalls).toEqual([]);
    });

    it('记忆态物品 → 原字形 #666666、不 interactive', () => {
        expect(itemAppearance(item, entityCtx({ cellVisible: false, cellHasMemory: true }))).toEqual({
            char: '!', color: '#666666', interactive: false,
        });
    });

    it('不可见且无记忆 → null', () => {
        expect(itemAppearance(item, entityCtx({ cellVisible: false, cellHasMemory: false }))).toBeNull();
    });
});

describe('R-1 entityAppearance：怪物', () => {
    it('hp ≤ 0 → null（死怪不画）', () => {
        expect(monsterAppearance(makeMonster({ hp: 0 }), entityCtx())).toBeNull();
        expect(monsterAppearance(makeMonster({ hp: -3 }), entityCtx({ cellVisible: true }))).toBeNull();
    });

    it('可见常态 → 原字形原色、interactive', () => {
        expect(monsterAppearance(makeMonster(), entityCtx())).toEqual({ char: 'r', color: 0xaa0044, interactive: true });
    });

    it('盟友 → #88ff88；睡眠 → 0x6688aa（数字字面量，逐位保留）', () => {
        expect(monsterAppearance(makeMonster({ isAlly: true }), entityCtx())!.color).toBe('#88ff88');
        const asleep = monsterAppearance(makeMonster({ state: MonsterState.ASLEEP }), entityCtx())!;
        expect(asleep.color).toBe(0x6688aa);
        expect(typeof asleep.color).toBe('number');
        // 盟友优先于睡眠（原 if / else if 结构）
        expect(monsterAppearance(makeMonster({ isAlly: true, state: MonsterState.ASLEEP }), entityCtx())!.color).toBe('#88ff88');
    });

    it('幻觉：单次 percent(35)，中 → 先取色再取字', () => {
        const cos = scriptedCosmetic([true]);
        const visual = monsterAppearance(makeMonster(), entityCtx({ hallucinating: true, cosmetic: cos }))!;
        expect(cos.percentCalls).toEqual([35]);
        expect(cos.pickSources).toEqual(['colors', 'chars']);
        expect(visual).toEqual({ char: '*', color: '#ff66ff', interactive: true });
    });

    it('幻觉不中 → 原样（但 percent 仍被消耗一次）', () => {
        const cos = scriptedCosmetic([false]);
        expect(monsterAppearance(makeMonster(), entityCtx({ hallucinating: true, cosmetic: cos }))!).toEqual({
            char: 'r', color: 0xaa0044, interactive: true,
        });
        expect(cos.percentCalls).toEqual([35]);
    });

    it('不可见 + 心灵感应 → #66ccff 剪影、不 interactive', () => {
        expect(monsterAppearance(makeMonster(), entityCtx({ cellVisible: false, telepathy: true }))).toEqual({
            char: 'r', color: '#66ccff', interactive: false,
        });
    });

    it('不可见 + 无心灵感应 → null', () => {
        expect(monsterAppearance(makeMonster(), entityCtx({ cellVisible: false, telepathy: false }))).toBeNull();
    });
});

describe('R-1 entityAppearance：玩家与统一入口', () => {
    it("玩家恒 '@' + #ffcc00、不 interactive", () => {
        expect(playerAppearance(new Player(5, 5))).toEqual({ char: '@', color: '#ffcc00', interactive: false });
    });

    it('entityAppearance 按实体类型正确分流', () => {
        const item = new Item('coin', '$', 0xffff00, ItemCategory.GOLD);
        const ctx = entityCtx();
        expect(entityAppearance(item, ctx)).toEqual(itemAppearance(item, ctx));
        expect(entityAppearance(makeMonster(), ctx)).toEqual(monsterAppearance(makeMonster(), ctx));
        expect(entityAppearance(new Player(1, 1), ctx)).toEqual(playerAppearance(new Player(1, 1)));
    });

    it('entityAppearance 对死怪同样返回 null', () => {
        expect(entityAppearance(makeMonster({ hp: 0 }), entityCtx())).toBeNull();
    });
});

// ════════════════════════ 结构守卫 ════════════════════════

describe('R-1 结构守卫：GameCanvas.vue 不得再出现外观决策', () => {
    const src = readFileSync(new URL('../components/GameCanvas.vue', import.meta.url), 'utf8');
    const templateIdx = src.indexOf('<template>');
    const scriptRegion = src.slice(0, templateIdx); // 两个 <script> 块（模板/样式在外）
    const setupIdx = src.indexOf('<script setup');
    const setupRegion = src.slice(setupIdx, templateIdx);

    it('颜色字面量多重集 == 豁免清单（逐条有理由，新增即红）', () => {
        const literals = (scriptRegion.match(/#[0-9a-fA-F]{6}\b|0x[0-9a-fA-F]{6}\b/g) ?? []).sort();
        // 豁免清单——全部是"绘制原语的静态底样式/画布清屏色"，不是格子/实体外观决策：
        //  0x111111 ×1  Pixi Application 画布清屏色（整幅画布的底，非任何一格的颜色）
        //  '#ffffff' ×2  Text sprite 与浮字的初始 fill（中性占位，每帧被 visual.color / ft.color 覆盖）
        //  '#ffff00' ×2  箭矢投射物 sprite 的初始 fill 与 dropShadow 色（每帧被 boltFrame 颜色覆盖）
        //  '#000000' ×1  浮字描边底色（每帧文字颜色来自 ft.color，描边本身是绘制原语）
        // W-2: 0xdddddd ×1，CE Items.c:6490 的中性瞄准格边框；
        // 仅绘制选择几何，不决定地形/怪物/物品外观。新增此绘制原语，其余豁免不变。
        expect(literals).toEqual(['#000000', '#ffff00', '#ffff00', '#ffffff', '#ffffff', '0x111111', '0xdddddd']);
    });

    it('没有字形字面量的 switch/case 分支（terrain 决策 switch 已迁出）', () => {
        expect((scriptRegion.match(/case '/g) ?? []).length).toBe(0);
    });

    it('决策 API 不得回流：TerrainType/GasType/MonsterState/ColorUtils/getTerrainVisual 零引用', () => {
        for (const marker of ['getTerrainVisual', 'TerrainType', 'GasType', 'MonsterState', 'ColorUtils']) {
            expect(scriptRegion.includes(marker), `script 区出现 "${marker}"`).toBe(false);
        }
    });

    it('render 里不得直接掷幻觉骰（只能经 ctx 注入 cosmeticPercent/cosmeticPick）', () => {
        expect((setupRegion.match(/cosmeticPercent\s*\(/g) ?? []).length).toBe(0);
        expect((setupRegion.match(/cosmeticPick\s*\(/g) ?? []).length).toBe(0);
        // 注入点必须在：外观函数从 ctx 拿到它们
        expect(setupRegion.includes('percent: cosmeticPercent')).toBe(true);
        expect(setupRegion.includes('pick: cosmeticPick')).toBe(true);
    });

    it('渲染必须经 Appearance 纯函数（防拆掉缝后手写决策）', () => {
        expect(scriptRegion.includes('engine/UI/Appearance')).toBe(true);
        for (const fn of ['cellAppearance(', 'itemAppearance(', 'monsterAppearance(', 'playerAppearance(']) {
            expect(setupRegion.includes(fn), `setup 区缺少 ${fn} 调用`).toBe(true);
        }
    });

    it('setup 区不得出现字形字面量赋值（char = "♠" 这类回流形态）', () => {
        expect((setupRegion.match(/\bchar\s*=\s*['"]/g) ?? []).length).toBe(0);
        for (const glyph of ['♠', '§', '⊙']) {
            expect(setupRegion.includes(glyph), `setup 区出现字形 "${glyph}"`).toBe(false);
        }
    });

    it('Appearance.ts 自身保持纯净：不 import 全局游戏单例', () => {
        const appearanceSrc = readFileSync(new URL('../engine/UI/Appearance.ts', import.meta.url), 'utf8');
        expect(appearanceSrc.includes('activeGame')).toBe(false);
        expect(appearanceSrc.includes('Core/Game')).toBe(false);
    });
});
