import i18next from 'i18next';
import type { GrowthValidationError } from './schema';

/** Only localization: data validation never changes the world or consumes randomness. */
export function growthDefinitionText(): Record<string, string> {
    return {
        "ext.growth.skill.steady-hand.name": i18next.t("ext.growth.skill.steady-hand.name", { defaultValue: "Steady Hand" }) ?? "Steady Hand",
        "ext.growth.skill.steady-hand.description": i18next.t("ext.growth.skill.steady-hand.description", { defaultValue: "Steady Hand configuration sample." }) ?? "Steady Hand configuration sample.",
        "ext.growth.skill.close-guard.name": i18next.t("ext.growth.skill.close-guard.name", { defaultValue: "Close Guard" }) ?? "Close Guard",
        "ext.growth.skill.close-guard.description": i18next.t("ext.growth.skill.close-guard.description", { defaultValue: "Close Guard configuration sample." }) ?? "Close Guard configuration sample.",
        "ext.growth.skill.careful-step.name": i18next.t("ext.growth.skill.careful-step.name", { defaultValue: "Careful Step" }) ?? "Careful Step",
        "ext.growth.skill.careful-step.description": i18next.t("ext.growth.skill.careful-step.description", { defaultValue: "Careful Step configuration sample." }) ?? "Careful Step configuration sample.",
        "ext.growth.skill.methodical.name": i18next.t("ext.growth.skill.methodical.name", { defaultValue: "Methodical" }) ?? "Methodical",
        "ext.growth.skill.methodical.description": i18next.t("ext.growth.skill.methodical.description", { defaultValue: "Methodical configuration sample." }) ?? "Methodical configuration sample.",
        "ext.growth.skill.composure.name": i18next.t("ext.growth.skill.composure.name", { defaultValue: "Composure" }) ?? "Composure",
        "ext.growth.skill.composure.description": i18next.t("ext.growth.skill.composure.description", { defaultValue: "Composure configuration sample." }) ?? "Composure configuration sample.",
        "ext.growth.skill.weapon-familiarity.name": i18next.t("ext.growth.skill.weapon-familiarity.name", { defaultValue: "Weapon Familiarity" }) ?? "Weapon Familiarity",
        "ext.growth.skill.weapon-familiarity.description": i18next.t("ext.growth.skill.weapon-familiarity.description", { defaultValue: "Weapon Familiarity configuration sample." }) ?? "Weapon Familiarity configuration sample.",
        "ext.growth.skill.measured-strike.name": i18next.t("ext.growth.skill.measured-strike.name", { defaultValue: "Measured Strike" }) ?? "Measured Strike",
        "ext.growth.skill.measured-strike.description": i18next.t("ext.growth.skill.measured-strike.description", { defaultValue: "Measured Strike configuration sample." }) ?? "Measured Strike configuration sample.",
        "ext.growth.skill.brace.name": i18next.t("ext.growth.skill.brace.name", { defaultValue: "Brace" }) ?? "Brace",
        "ext.growth.skill.brace.description": i18next.t("ext.growth.skill.brace.description", { defaultValue: "Brace configuration sample." }) ?? "Brace configuration sample.",
        "ext.growth.skill.withdraw.name": i18next.t("ext.growth.skill.withdraw.name", { defaultValue: "Withdraw" }) ?? "Withdraw",
        "ext.growth.skill.withdraw.description": i18next.t("ext.growth.skill.withdraw.description", { defaultValue: "Withdraw configuration sample." }) ?? "Withdraw configuration sample.",
        "ext.growth.skill.hold-breath.name": i18next.t("ext.growth.skill.hold-breath.name", { defaultValue: "Hold Breath" }) ?? "Hold Breath",
        "ext.growth.skill.hold-breath.description": i18next.t("ext.growth.skill.hold-breath.description", { defaultValue: "Hold Breath configuration sample." }) ?? "Hold Breath configuration sample.",
        "ext.growth.skill.survey.name": i18next.t("ext.growth.skill.survey.name", { defaultValue: "Survey" }) ?? "Survey",
        "ext.growth.skill.survey.description": i18next.t("ext.growth.skill.survey.description", { defaultValue: "Survey configuration sample." }) ?? "Survey configuration sample.",
        "ext.growth.skill.pressure.name": i18next.t("ext.growth.skill.pressure.name", { defaultValue: "Pressure" }) ?? "Pressure",
        "ext.growth.skill.pressure.description": i18next.t("ext.growth.skill.pressure.description", { defaultValue: "Pressure configuration sample." }) ?? "Pressure configuration sample.",
        "ext.growth.profession.guardian.name": i18next.t("ext.growth.profession.guardian.name", { defaultValue: "Guardian" }) ?? "Guardian",
        "ext.growth.profession.guardian.description": i18next.t("ext.growth.profession.guardian.description", { defaultValue: "Guardian configuration sample." }) ?? "Guardian configuration sample.",
        "ext.growth.profession.scout.name": i18next.t("ext.growth.profession.scout.name", { defaultValue: "Scout" }) ?? "Scout",
        "ext.growth.profession.scout.description": i18next.t("ext.growth.profession.scout.description", { defaultValue: "Scout configuration sample." }) ?? "Scout configuration sample.",
        "ext.growth.profession.explorer.name": i18next.t("ext.growth.profession.explorer.name", { defaultValue: "Explorer" }) ?? "Explorer",
        "ext.growth.profession.explorer.description": i18next.t("ext.growth.profession.explorer.description", { defaultValue: "Explorer configuration sample." }) ?? "Explorer configuration sample.",
        "ext.growth.profession.skirmisher.name": i18next.t("ext.growth.profession.skirmisher.name", { defaultValue: "Skirmisher" }) ?? "Skirmisher",
        "ext.growth.profession.skirmisher.description": i18next.t("ext.growth.profession.skirmisher.description", { defaultValue: "Skirmisher configuration sample." }) ?? "Skirmisher configuration sample.",
        "ext.growth.lineage.human.name": i18next.t("ext.growth.lineage.human.name", { defaultValue: "Human" }) ?? "Human",
        "ext.growth.lineage.human.description": i18next.t("ext.growth.lineage.human.description", { defaultValue: "Human configuration sample." }) ?? "Human configuration sample.",
        "ext.growth.lineage.stoneborn.name": i18next.t("ext.growth.lineage.stoneborn.name", { defaultValue: "Stoneborn" }) ?? "Stoneborn",
        "ext.growth.lineage.stoneborn.description": i18next.t("ext.growth.lineage.stoneborn.description", { defaultValue: "Stoneborn configuration sample." }) ?? "Stoneborn configuration sample.",
        "ext.growth.lineage.duskborn.name": i18next.t("ext.growth.lineage.duskborn.name", { defaultValue: "Duskborn" }) ?? "Duskborn",
        "ext.growth.lineage.duskborn.description": i18next.t("ext.growth.lineage.duskborn.description", { defaultValue: "Duskborn configuration sample." }) ?? "Duskborn configuration sample.",
        "ext.growth.lineage.reedfolk.name": i18next.t("ext.growth.lineage.reedfolk.name", { defaultValue: "Reedfolk" }) ?? "Reedfolk",
        "ext.growth.lineage.reedfolk.description": i18next.t("ext.growth.lineage.reedfolk.description", { defaultValue: "Reedfolk configuration sample." }) ?? "Reedfolk configuration sample.",
        "ext.growth.faith.unaffiliated.name": i18next.t("ext.growth.faith.unaffiliated.name", { defaultValue: "Own Path" }) ?? "Own Path",
        "ext.growth.faith.unaffiliated.description": i18next.t("ext.growth.faith.unaffiliated.description", { defaultValue: "Own Path configuration sample." }) ?? "Own Path configuration sample.",
        "ext.growth.oath.watch.description": i18next.t("ext.growth.oath.watch.description", { defaultValue: "Stronger brace mitigation costs a longer cooldown." }) ?? "Stronger brace mitigation costs a longer cooldown.",
        "ext.growth.faith.watch.name": i18next.t("ext.growth.faith.watch.name", { defaultValue: "Watch Oath" }) ?? "Watch Oath",
        "ext.growth.faith.watch.description": i18next.t("ext.growth.faith.watch.description", { defaultValue: "Watch Oath configuration sample." }) ?? "Watch Oath configuration sample.",
        "ext.growth.oath.path.description": i18next.t("ext.growth.oath.path.description", { defaultValue: "A first depth visit restores focus at the cost of capacity." }) ?? "A first depth visit restores focus at the cost of capacity.",
        "ext.growth.faith.path.name": i18next.t("ext.growth.faith.path.name", { defaultValue: "Path Oath" }) ?? "Path Oath",
        "ext.growth.faith.path.description": i18next.t("ext.growth.faith.path.description", { defaultValue: "Path Oath configuration sample." }) ?? "Path Oath configuration sample.",
        "ext.growth.oath.restraint.description": i18next.t("ext.growth.oath.restraint.description", { defaultValue: "Higher focus capacity costs a longer recovery interval." }) ?? "Higher focus capacity costs a longer recovery interval.",
        "ext.growth.faith.restraint.name": i18next.t("ext.growth.faith.restraint.name", { defaultValue: "Restraint Oath" }) ?? "Restraint Oath",
        "ext.growth.faith.restraint.description": i18next.t("ext.growth.faith.restraint.description", { defaultValue: "Restraint Oath configuration sample." }) ?? "Restraint Oath configuration sample.",
        "ext.growth.attribute.strength-training.name": i18next.t("ext.growth.attribute.strength-training.name", { defaultValue: "Strength Training" }) ?? "Strength Training",
        "ext.growth.attribute.strength-training.description": i18next.t("ext.growth.attribute.strength-training.description", { defaultValue: "Strength Training configuration sample." }) ?? "Strength Training configuration sample.",
        "ext.growth.attribute.agility.name": i18next.t("ext.growth.attribute.agility.name", { defaultValue: "Agility" }) ?? "Agility",
        "ext.growth.attribute.agility.description": i18next.t("ext.growth.attribute.agility.description", { defaultValue: "Agility configuration sample." }) ?? "Agility configuration sample.",
        "ext.growth.attribute.constitution.name": i18next.t("ext.growth.attribute.constitution.name", { defaultValue: "Constitution" }) ?? "Constitution",
        "ext.growth.attribute.constitution.description": i18next.t("ext.growth.attribute.constitution.description", { defaultValue: "Constitution configuration sample." }) ?? "Constitution configuration sample.",
        "ext.growth.attribute.will.name": i18next.t("ext.growth.attribute.will.name", { defaultValue: "Will" }) ?? "Will",
        "ext.growth.attribute.will.description": i18next.t("ext.growth.attribute.will.description", { defaultValue: "Will configuration sample." }) ?? "Will configuration sample.",
        "ext.growth.attribute.perception.name": i18next.t("ext.growth.attribute.perception.name", { defaultValue: "Perception" }) ?? "Perception",
        "ext.growth.attribute.perception.description": i18next.t("ext.growth.attribute.perception.description", { defaultValue: "Perception configuration sample." }) ?? "Perception configuration sample.",
        "ext.growth.template.neutral.name": i18next.t("ext.growth.template.neutral.name", { defaultValue: "Neutral Growth" }) ?? "Neutral Growth",
        "ext.growth.template.neutral.description": i18next.t("ext.growth.template.neutral.description", { defaultValue: "Neutral Growth configuration sample." }) ?? "Neutral Growth configuration sample.",
        "ext.growth.error.json": i18next.t("ext.growth.error.json", { defaultValue: "Growth data must be finite acyclic JSON: {{path}}" }) ?? "Growth data must be finite acyclic JSON: {{path}}",
        "ext.growth.error.shape": i18next.t("ext.growth.error.shape", { defaultValue: "Invalid growth field type: {{path}}" }) ?? "Invalid growth field type: {{path}}",
        "ext.growth.error.field": i18next.t("ext.growth.error.field", { defaultValue: "Missing or unknown growth field: {{path}}" }) ?? "Missing or unknown growth field: {{path}}",
        "ext.growth.error.range": i18next.t("ext.growth.error.range", { defaultValue: "Growth value is out of range: {{path}}" }) ?? "Growth value is out of range: {{path}}",
        "ext.growth.error.duplicate": i18next.t("ext.growth.error.duplicate", { defaultValue: "Duplicate growth identifier: {{path}}" }) ?? "Duplicate growth identifier: {{path}}",
        "ext.growth.error.reference": i18next.t("ext.growth.error.reference", { defaultValue: "Missing or wrong-kind growth reference: {{path}}" }) ?? "Missing or wrong-kind growth reference: {{path}}",
        "ext.growth.error.cycle": i18next.t("ext.growth.error.cycle", { defaultValue: "Skill prerequisites contain a cycle: {{path}}" }) ?? "Skill prerequisites contain a cycle: {{path}}",
        "ext.growth.error.version": i18next.t("ext.growth.error.version", { defaultValue: "Growth data and module versions differ: {{path}}" }) ?? "Growth data and module versions differ: {{path}}",
        "ext.growth.error.text": i18next.t("ext.growth.error.text", { defaultValue: "Missing growth localization text: {{path}}" }) ?? "Missing growth localization text: {{path}}",
        "ext.growth.error.budget": i18next.t("ext.growth.error.budget", { defaultValue: "Growth data exceeds its declared budget: {{path}}" }) ?? "Growth data exceeds its declared budget: {{path}}",
    };
}

export function formatGrowthValidationError(error: GrowthValidationError): string {
    const localized = growthDefinitionText()[error.key]!.replace('{{path}}', error.path);
    return error.detail ? `${localized} (${error.detail})` : localized;
}
