import {chromium} from 'playwright';import fs from 'node:fs';import assert from 'node:assert/strict';
const out='ai_docs/reports/u-17c-evidence',errors=[],results=[];
const browser=await chromium.launch({headless:false});
try{
 const page=await browser.newPage({viewport:{width:1280,height:900}});
 page.on('dialog',d=>d.accept());page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('http://127.0.0.1:5199');await page.locator('.menu-card input[type=text]').fill('1719');await page.locator('.menu-card .actions button').first().click();await page.waitForFunction(()=>!!window.activeGame?.onRenderRequested);
 const snap=async name=>{await page.waitForTimeout(160);await page.screenshot({path:`${out}/browser-${name}.png`});results.push({name,state:JSON.parse(await page.evaluate(()=>window.render_game_to_text()))});};
 async function scene(){await page.evaluate(async()=>{
  const g=window.activeGame;g.startNewGame({seed:1719,mode:'test'});g.animationEnabled=false;g.monsters=[];g.dormantMonsters=[];g.items=[];g.purgatory=[];
  const {TerrainType:T}=await import('/src/engine/Map/Grid.ts');
  for(let x=1;x<g.grid.width-1;x++)for(let y=1;y<g.grid.height-1;y++){g.grid.setTerrain(x,y,T.FLOOR);const c=g.grid.getCell(x,y);c.machineNumber=0;c.volume=0;}
  g.player.loc={x:10,y:10};g.player.hp=g.player.maxHp=100;g.player.statusDurations={};g.secretScanDepth=-1;g.bindDormantAwakener();g.needsRender=true;g.updateVision();g.update();g.onRenderRequested();
 });}
 await snap('natural');
 await scene();await page.evaluate(async()=>{const {TerrainType:T}=await import('/src/engine/Map/Grid.ts');const g=window.activeGame;for(const [x,y,t] of [[11,10,T.PRESSURE_PLATE],[16,10,T.PORTCULLIS_CLOSED]]){g.grid.setTerrain(x,y,t);g.grid.getCell(x,y).machineNumber=7;}g.needsRender=true;g.updateVision();g.update();});await snap('pressure-before');await page.keyboard.press('ArrowRight');
 const pressure=await page.evaluate(async()=>{const {TerrainType:T}=await import('/src/engine/Map/Grid.ts');const g=window.activeGame;return{plate:g.grid.getCell(11,10).terrain,expected:T.MACHINE_PRESSURE_PLATE_USED,gate:g.grid.getCell(16,10).terrain,open:T.PORTCULLIS_DORMANT};});assert.equal(pressure.plate,pressure.expected);assert.equal(pressure.gate,pressure.open);results.push({pressure});await snap('pressure-used');
 await scene();await page.evaluate(async()=>{const {TerrainType:T}=await import('/src/engine/Map/Grid.ts');const g=window.activeGame;for(const [x,y,t] of [[11,10,T.WALL_LEVER_HIDDEN],[16,10,T.PORTCULLIS_CLOSED]]){g.grid.setTerrain(x,y,t);g.grid.getCell(x,y).machineNumber=7;}g.needsRender=true;g.updateVision();g.update();});await snap('lever-hidden');for(let n=0;n<5;n++)await page.keyboard.press('s');await snap('lever-revealed');await page.keyboard.press('ArrowRight');
 const lever=await page.evaluate(async()=>{const {TerrainType:T}=await import('/src/engine/Map/Grid.ts');const g=window.activeGame;return{loc:{...g.player.loc},lever:g.grid.getCell(11,10).terrain,expected:T.WALL_LEVER_PULLED,gate:g.grid.getCell(16,10).terrain,open:T.PORTCULLIS_DORMANT};});assert.deepEqual(lever.loc,{x:10,y:10});assert.equal(lever.lever,lever.expected);assert.equal(lever.gate,lever.open);results.push({lever});await snap('lever-pulled');
 await scene();await page.evaluate(async()=>{const {TerrainType:T}=await import('/src/engine/Map/Grid.ts');const g=window.activeGame;g.grid.setTerrain(11,10,T.TRAP_DOOR_HIDDEN);g.needsRender=true;g.updateVision();g.update();});for(let n=0;n<5;n++)await page.keyboard.press('s');
 const hole=await page.evaluate(async()=>{const {TerrainType:T}=await import('/src/engine/Map/Grid.ts');const g=window.activeGame;return{layers:g.grid.getCell(11,10).layers,expected:[T.FLOOR,T.TRAP_DOOR,T.NOTHING,T.NOTHING]};});assert.deepEqual(hole.layers,hole.expected);results.push({hole});await snap('trapdoor-found');await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>window.activeGame.depth),2);await snap('trapdoor-d2');
 await scene();await page.evaluate(async()=>{const {TerrainType:T,DungeonLayer:L}=await import('/src/engine/Map/Grid.ts');const g=window.activeGame;g.grid.setTerrain(11,10,T.CARPET);g.grid.setTerrainLayer(11,10,L.LIQUID,T.MACHINE_TRIGGER_FLOOR_REPEATING);g.grid.setTerrain(16,10,T.RESURRECTION_ALTAR);g.grid.getCell(11,10).machineNumber=g.grid.getCell(16,10).machineNumber=7;g.needsRender=true;g.updateVision();g.update();});await page.keyboard.press('ArrowRight');
 const empty=await page.evaluate(async()=>{const {TerrainType:T}=await import('/src/engine/Map/Grid.ts');const g=window.activeGame;return{altar:g.grid.getCell(16,10).terrain,expected:T.RESURRECTION_ALTAR};});assert.equal(empty.altar,empty.expected);await snap('repeating-empty');
 await page.evaluate(async()=>{const g=window.activeGame;const {Monster}=await import('/src/entities/Monster.ts');const {default:rows}=await import('/src/data/monsters.json');const m=new Monster(15,10,rows.find(m=>m.id==='goblin'));m.isAlly=true;m.hp=0;g.purgatory.push(m);window.u17cAlly=m;});await page.keyboard.press('.');
 const raised=await page.evaluate(async()=>{const {TerrainType:T}=await import('/src/engine/Map/Grid.ts');const g=window.activeGame;return{count:g.purgatory.length,alive:g.monsters.includes(window.u17cAlly),hp:window.u17cAlly.hp,floor:g.grid.getCell(11,10).layers[1],expected:T.MACHINE_TRIGGER_FLOOR_REPEATING};});assert.equal(raised.count,0);assert(raised.alive&&raised.hp>0);assert.equal(raised.floor,raised.expected);results.push({empty,raised});await snap('repeating-raised');
 // Use the actual whole CE22 blueprint. No direct DF cast substitutes for its build source.
 await scene();const tutorial=await page.evaluate(async()=>{
  const g=window.activeGame;const {TerrainType:T}=await import('/src/engine/Map/Grid.ts');const {BlueprintEngine}=await import('/src/engine/Generator/BlueprintEngine.ts');const {default:blueprints}=await import('/src/data/blueprints.json');const {rng}=await import('/src/engine/Random.ts');const {Item,ItemCategory}=await import('/src/engine/Items/Item.ts');
  for(let x=0;x<g.grid.width;x++)for(let y=0;y<g.grid.height;y++)g.grid.setTerrain(x,y,T.GRANITE);
  const cells=[];for(let x=6;x<=20;x++)for(let y=6;y<=13;y++){g.grid.setTerrain(x,y,T.FLOOR);cells.push({x,y});}
  const bp=blueprints.find(b=>b.ceBlueprintId===22);rng.seedRandomGenerator(20260920);const result=new BlueprintEngine(g.grid,2,[bp]).applyBlueprint(bp,{cells,center:{x:13,y:9},door:{x:6,y:9}});if(!result)throw Error('CE22 failed');
  const plate=cells.find(p=>g.grid.getCell(p.x,p.y).layers.includes(T.PRESSURE_PLATE));const origin=cells.find(p=>Math.max(Math.abs(p.x-plate.x),Math.abs(p.y-plate.y))===3&&g.grid.getCell(p.x,p.y).isPassable&&!g.grid.getCell(p.x,p.y).layers.includes(T.TRAP_DOOR));g.player.loc={...origin};
  const i=new Item('长剑',')',0xffffff,ItemCategory.WEAPON);g.player.inventory.addItem(i);g.enterThrowMode(i);window.u17cPlate=plate;g.needsRender=true;g.updateVision();g.update();return{plate,origin,holes:cells.filter(p=>g.grid.getCell(p.x,p.y).layers.includes(T.TRAP_DOOR)).length};
 });assert(tutorial.holes>0);await snap('medium-hole-tutorial');
 // Match the SFC's own layout transform, then click the actual target cell.
 const box=await page.locator('canvas').boundingBox();const layout=await page.evaluate(async({w,h})=>{const {computeMapLayout}=await import('/src/components/GameCanvas.vue');return computeMapLayout(w,h);},{w:box.width,h:box.height});
 await page.mouse.click(box.x+layout.offsetX+(tutorial.plate.x+.5)*16*layout.scaleX,box.y+layout.offsetY+(tutorial.plate.y+.5)*16*layout.scaleY);
 const thrown=await page.evaluate(async()=>{const {TerrainType:T}=await import('/src/engine/Map/Grid.ts');const g=window.activeGame,p=window.u17cPlate;return{plate:g.grid.getCell(p.x,p.y).terrain,expected:T.MACHINE_PRESSURE_PLATE_USED,exitPassable:g.canMoveTo(6,9),isThrowing:g.isThrowing};});results.push({tutorial,thrown});await snap('medium-hole-after-input');assert.equal(thrown.plate,thrown.expected);assert(thrown.exitPassable);assert.equal(thrown.isThrowing,false);results.push({tutorial,thrown});await snap('medium-hole-solved');
 await page.setViewportSize({width:700,height:900});await snap('narrow');assert.deepEqual(errors,[]);
}finally{fs.writeFileSync(`${out}/browser-results.json`,JSON.stringify({errors,results},null,2)+'\n');await browser.close();}
